/**
 * Ministry Attendance API
 * This API is created as part of ministry attendance program
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { AttendeeSignIn } from '../model/attendeeSignIn';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';


@Injectable()
export class MinisterService {

    protected basePath = 'http://localhost:9999/ministry';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Registers member attendance
     * Registers member attendance
     * @param attendeeSignIn passing member and meeting details for attendee sign in
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public memberRegister(attendeeSignIn: AttendeeSignIn, observe?: 'body', reportProgress?: boolean): Observable<AttendeeSignIn>;
    public memberRegister(attendeeSignIn: AttendeeSignIn, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AttendeeSignIn>>;
    public memberRegister(attendeeSignIn: AttendeeSignIn, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AttendeeSignIn>>;
    public memberRegister(attendeeSignIn: AttendeeSignIn, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (attendeeSignIn === null || attendeeSignIn === undefined) {
            throw new Error('Required parameter attendeeSignIn was null or undefined when calling memberRegister.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AttendeeSignIn>(`${this.basePath}/attendance`,
            attendeeSignIn,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
