select * from
(select a.id, a.name, b.mobile1, b.address_num || ' ' || (select name from streets where id = b.address_street) || ' ' || (select name from regions where id = b.address_region) || ' ' || (select name from districts where id = b.address_district) || ' ' || b.address_free as address from member a, contact b where a.id = b.id and a.id = 6) a,
(select count(1) as today_ministry_attendance from child_ministry_attendance where id = 6 and action_date = to_date('31-07-2015', 'dd-mm-yyyy')) b,
(select (b.total_count - a.attendance_count) as ministry_total_gheyab from (select count(1) as attendance_count from child_ministry_attendance where id = 6 and action_date >= (select to_date(value, 'dd-mm-yyyy') from nvpair where name = 'ministry_start_date')) a, (select (((to_date('31-07-2015', 'dd-mm-yyyy') - to_date(value, 'dd-mm-yyyy')) / 7) + 1) as total_count from nvpair where name = 'ministry_start_date') b) c,
(select count(1) as total_followup_by_phone from child_followup where id = 6 and followup_by = (select id from followup_methods where des = 'ãßÇáãÉ ÊáíÝæäíÉ') and action_date >= (select to_date(value, 'dd-mm-yyyy') from nvpair where name = 'ministry_start_date')) d,
(select count(1) as total_followup_by_home from child_followup where id = 6 and followup_by = (select id from followup_methods where des = 'ÒíÇÑÉ ãäÒáíÉ') and action_date >= (select to_date(value, 'dd-mm-yyyy') from nvpair where name = 'ministry_start_date')) e,
(select nvl(a.count, (select (((to_date('31-07-2015', 'dd-mm-yyyy') - to_date(value, 'dd-mm-yyyy')) / 7) + 1) from nvpair where name = 'ministry_start_date')) as mass_gheyab_motataly from (select ((to_date('31-07-2015', 'dd-mm-yyyy') - max(action_date)) / 7) as count from child_mass_attendance where id = 6) a) f,
(select decode(count(1), 0, 'áÇ', 'äÚã') as today_mass_attendance from child_mass_attendance where id = 6 and action_date = to_date('31-07-2015', 'dd-mm-yyyy')) g,
(select nvl(a.count, (select (((to_date('31-07-2015', 'dd-mm-yyyy') - to_date(value, 'dd-mm-yyyy')) / 7) + 1) from nvpair where name = 'ministry_start_date')) as ministry_gheyab_motataly from (select ((to_date('31-07-2015', 'dd-mm-yyyy') - max(action_date)) / 7) as count from child_ministry_attendance where id = 6) a) h,
(select count(1) as eftqad_motataly from child_followup where action_date >= (select nvl(a.max_date, (select to_date(value, 'dd-mm-yyyy') from nvpair where name = 'ministry_start_date')) from (select max(action_date) as max_date from child_ministry_attendance where id = 6) a) and id = 6) i